branches:
  only: 
    - master

language: python

# http://docs.travis-ci.com/user/languages/python/
python:
 - 3.3
 - 3.4
 - 3.5
 - 3.6
 - 3.7

# http://docs.travis-ci.com/user/multi-os/
os:
 - linux

install:
 - pip install --upgrade -q pip
 - pip install -r requirements.txt

script: make test